many fixes?

diff --git a/build_singularity_el7 b/build_singularity_el7
--- a/build_singularity_el7
+++ b/build_singularity_el7
@@ -14,11 +14,12 @@ if [[ "${1}" == "sandbox" ]]; then
 fi
 [[ -e "${NAME}" ]] && rm -f "${NAME}"
 
-sudo -E singularity build ${DO_SANDBOX} "${NAME}" "${SING_CONF}"
+singularity remote login -u asevcenc -p "$(< ~/gitlab_cern.token)" docker://gitlab-registry.cern.ch && \
+singularity build --fakeroot ${DO_SANDBOX} "${NAME}" "${SING_CONF}" || { echo "Build failed!"; exit 1; }
 
 [[ -n "${DO_SANDBOX}" ]] && sudo chown -R ${U}:${G} "${NAME}"
 sudo chown -R ${U}:${G} "${SINGULARITY_CACHEDIR:-${HOME}/.singularity/cache}"
 
-oras login -u asevcenc -p "$(< ~/registry-cern.token)" registry.cern.ch
+oras login -u robot-asevcenc+asevcenc_push -p $(< ~/registry-cern-robot.token) registry.cern.ch
 oras push registry.cern.ch/asevcenc/$(basename ${NAME} .sif):latest ${NAME}:application/vnd.sylabs.sif.layer.v1.sif && echo "Done" || echo "Fail"
 
